apiVersion: v1
kind: Secret
metadata:
  name: ttrpg-api-secret
  namespace: ttrpg
type: Opaque
stringData:
  Jwt__Key: "ChangeThisKubernetesJwtSigningKeyToARealLongRandomValue123!"
  Seed__AdminPassword: "ChangeThisKubernetesAdminPassword123!"
