<#
.SYNOPSIS
    Generates k8s/sealed-secret.yaml using Bitnami Sealed Secrets and kubeseal.

.DESCRIPTION
    Reads secret values (JWT key and admin password), wraps them in a temporary
    plain Kubernetes Secret manifest, pipes it through kubeseal to produce an
    encrypted SealedSecret, and writes the result to k8s/sealed-secret.yaml.

    The output file is safe to commit to git. The plain values are never written
    to disk — they exist only in memory during this script.

.PARAMETER JwtKey
    The JWT signing key (min 32 characters). Prompted interactively if omitted.

.PARAMETER AdminPassword
    The seeded admin account password. Prompted interactively if omitted.

.PARAMETER Namespace
    Kubernetes namespace for the secret. Defaults to 'ttrpg'.

.PARAMETER SecretName
    Name of the Kubernetes Secret / SealedSecret resource. Defaults to 'ttrpg-api-secret'.

.EXAMPLE
    .\scripts\seal-secrets.ps1

.EXAMPLE
    .\scripts\seal-secrets.ps1 -JwtKey "my-key" -AdminPassword "MyPass1!"

.NOTES
    Prerequisites:
      1. kubectl connected to your target cluster.
      2. Sealed Secrets controller installed in the cluster:
           kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.3/controller.yaml
      3. kubeseal CLI installed:
           https://github.com/bitnami-labs/sealed-secrets/releases
           (Windows: download kubeseal.exe and add to PATH)
#>
[CmdletBinding()]
param(
    [string]$JwtKey,
    [string]$AdminPassword,
    [string]$Namespace = "ttrpg",
    [string]$SecretName = "ttrpg-api-secret"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Join-Path $PSScriptRoot ".."
$outputPath = Join-Path $repoRoot "k8s\sealed-secret.yaml"

function Assert-Command([string]$name, [string]$installHint) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        Write-Error "$name was not found. $installHint"
        exit 1
    }
}

Assert-Command "kubectl"  "Install kubectl: https://kubernetes.io/docs/tasks/tools/"
Assert-Command "kubeseal" "Install kubeseal: https://github.com/bitnami-labs/sealed-secrets/releases"

# Verify cluster connectivity
Write-Host "Verifying cluster connectivity..."
kubectl cluster-info --request-timeout=5s | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error "kubectl cannot reach the cluster. Check your kubeconfig and cluster status."
    exit 1
}

# Verify the Sealed Secrets controller is present
$controllerPod = kubectl get pods -n kube-system -l name=sealed-secrets-controller -o name 2>$null
if (-not $controllerPod) {
    Write-Warning "No Sealed Secrets controller pod found in kube-system."
    Write-Warning "Install it with:"
    Write-Warning "  kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.3/controller.yaml"
    Write-Warning "Then re-run this script."
    exit 1
}

# Collect secrets
if (-not $JwtKey) {
    $JwtKey = Read-Host "Enter JWT signing key (min 32 characters, press Enter to generate)"
    if (-not $JwtKey) {
        Write-Host "Generating a secure JWT key..."
        $bytes = New-Object byte[] 48
        $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
        try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
        $JwtKey = [Convert]::ToBase64String($bytes)
        Write-Host "Generated key: $JwtKey"
        Write-Host "(Save this somewhere safe — you will need it to rotate secrets later.)"
    }
}

if ($JwtKey.Length -lt 32) {
    Write-Error "JWT key must be at least 32 characters long."
    exit 1
}

if (-not $AdminPassword) {
    $securePass = Read-Host "Enter admin password (min 12 chars, uppercase + digit required)" -AsSecureString
    $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePass)
    )
}

if ($AdminPassword.Length -lt 12) {
    Write-Error "Admin password must be at least 12 characters."
    exit 1
}
if ($AdminPassword -notmatch '[A-Z]') {
    Write-Error "Admin password must contain at least one uppercase letter."
    exit 1
}
if ($AdminPassword -notmatch '\d') {
    Write-Error "Admin password must contain at least one digit."
    exit 1
}

# Build the plain Secret manifest in memory (never written to disk)
$plainSecretYaml = @"
apiVersion: v1
kind: Secret
metadata:
  name: $SecretName
  namespace: $Namespace
type: Opaque
stringData:
  Jwt__Key: "$JwtKey"
  Seed__AdminPassword: "$AdminPassword"
"@

Write-Host "Sealing secret with kubeseal..."
$sealedYaml = $plainSecretYaml | kubeseal `
    --format yaml `
    --namespace $Namespace `
    --name $SecretName `
    2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Error "kubeseal failed:`n$sealedYaml"
    exit 1
}

# Prepend a safety comment
$header = @"
# SealedSecret — generated by scripts/seal-secrets.ps1 on $(Get-Date -Format 'yyyy-MM-dd').
# This file is SAFE TO COMMIT. Encrypted values are decryptable only by the
# Sealed Secrets controller in the cluster this was generated against.
#
# To regenerate: .\scripts\seal-secrets.ps1
"@

"$header`n$sealedYaml" | Set-Content -Path $outputPath -Encoding UTF8

Write-Host ""
Write-Host "Sealed secret written to: k8s/sealed-secret.yaml"
Write-Host "This file is safe to commit to git."
Write-Host ""
Write-Host "Apply to cluster:"
Write-Host "  kubectl apply -k k8s/"
