// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesApi.Data;

#nullable disable

namespace NotesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NotesApi.Models.ActionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorNpcId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChainStep")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CombatEncounterId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CombatRound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DmDifficultyModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EffectiveDc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavourText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingChainEffectsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollChainStateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionModeAtSubmit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SkillCheckBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillCheckGroupLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetNpcId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CombatEncounterId");

                    b.HasIndex("ParentActionId");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("ActionRequests");
                });

            modelBuilder.Entity("NotesApi.Models.ActionResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalActions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatChangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionRequestId")
                        .IsUnique();

                    b.ToTable("ActionResolutions");
                });

            modelBuilder.Entity("NotesApi.Models.ActionRollPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoResolveOutcome")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainStepKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCheckText")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DmRolled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuidanceText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RollResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetCharacterId");

                    b.HasIndex("ActionRequestId", "Status");

                    b.ToTable("ActionRollPrompts");
                });

            modelBuilder.Entity("NotesApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NotesApi.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("NotesApi.Models.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignMembers");
                });

            modelBuilder.Entity("NotesApi.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusEffectsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Name")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("NotesApi.Models.CombatEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromptedTurnCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("CombatEncounters");
                });

            modelBuilder.Entity("NotesApi.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DmUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RulesetCode");

                    b.HasIndex("DmUserId", "CreatedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NotesApi.Models.GameParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinToken")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("JoinToken")
                        .IsUnique();

                    b.HasIndex("GameId", "DisplayName");

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("NotesApi.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveCombatEncounterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveTurnParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiceRollMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("NpcVisibilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCombatEncounterId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("GameId", "StartedAt");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("NotesApi.Models.InitiativeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CombatantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CombatantName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("CombatantType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitiativeScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentTurn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("InitiativeEntries");
                });

            modelBuilder.Entity("NotesApi.Models.NpcOrMonster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatBlockJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusEffectsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Name");

                    b.ToTable("NpcsAndMonsters");
                });

            modelBuilder.Entity("NotesApi.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NotesApi.Models.Ruleset", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterTemplateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiceNotation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("NotesApi.Models.ScheduledSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrenceCron")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedSessionId");

                    b.HasIndex("CampaignId", "ScheduledAt");

                    b.ToTable("ScheduledSessions");
                });

            modelBuilder.Entity("NotesApi.Models.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId", "UpdatedAt");

                    b.HasIndex("SessionId", "OwnerKind", "OwnerId")
                        .IsUnique();

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("NotesApi.Models.SessionRollPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActionRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCheckText")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuidanceText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RollResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SkillCheckBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionRequestId");

                    b.HasIndex("TargetCharacterId");

                    b.HasIndex("SessionId", "Status");

                    b.ToTable("SessionRollPrompts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NotesApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NotesApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NotesApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotesApi.Models.ActionRequest", b =>
                {
                    b.HasOne("NotesApi.Models.CombatEncounter", "CombatEncounter")
                        .WithMany("Actions")
                        .HasForeignKey("CombatEncounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotesApi.Models.ActionRequest", "ParentAction")
                        .WithMany("ChildActions")
                        .HasForeignKey("ParentActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotesApi.Models.GameSession", "Session")
                        .WithMany("Actions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatEncounter");

                    b.Navigation("ParentAction");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NotesApi.Models.ActionResolution", b =>
                {
                    b.HasOne("NotesApi.Models.ActionRequest", "ActionRequest")
                        .WithOne("Resolution")
                        .HasForeignKey("NotesApi.Models.ActionResolution", "ActionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRequest");
                });

            modelBuilder.Entity("NotesApi.Models.ActionRollPrompt", b =>
                {
                    b.HasOne("NotesApi.Models.ActionRequest", "ActionRequest")
                        .WithMany("RollPrompts")
                        .HasForeignKey("ActionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRequest");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("NotesApi.Models.Campaign", b =>
                {
                    b.HasOne("NotesApi.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NotesApi.Models.CampaignMember", b =>
                {
                    b.HasOne("NotesApi.Models.Campaign", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotesApi.Models.Character", b =>
                {
                    b.HasOne("NotesApi.Models.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NotesApi.Models.CombatEncounter", b =>
                {
                    b.HasOne("NotesApi.Models.GameSession", "Session")
                        .WithMany("CombatEncounters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NotesApi.Models.Game", b =>
                {
                    b.HasOne("NotesApi.Models.ApplicationUser", "DmUser")
                        .WithMany("GamesHosted")
                        .HasForeignKey("DmUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DmUser");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("NotesApi.Models.GameParticipant", b =>
                {
                    b.HasOne("NotesApi.Models.Character", "Character")
                        .WithMany("Participants")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NotesApi.Models.GameSession", b =>
                {
                    b.HasOne("NotesApi.Models.CombatEncounter", "ActiveCombatEncounter")
                        .WithMany()
                        .HasForeignKey("ActiveCombatEncounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotesApi.Models.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCombatEncounter");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NotesApi.Models.InitiativeEntry", b =>
                {
                    b.HasOne("NotesApi.Models.GameSession", "Session")
                        .WithMany("InitiativeEntries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NotesApi.Models.NpcOrMonster", b =>
                {
                    b.HasOne("NotesApi.Models.Game", "Game")
                        .WithMany("NpcsAndMonsters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NotesApi.Models.RefreshToken", b =>
                {
                    b.HasOne("NotesApi.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotesApi.Models.ScheduledSession", b =>
                {
                    b.HasOne("NotesApi.Models.Campaign", "Campaign")
                        .WithMany("ScheduledSessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.GameSession", "LinkedSession")
                        .WithMany()
                        .HasForeignKey("LinkedSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("LinkedSession");
                });

            modelBuilder.Entity("NotesApi.Models.SessionNote", b =>
                {
                    b.HasOne("NotesApi.Models.GameSession", "Session")
                        .WithMany("SessionNotes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NotesApi.Models.SessionRollPrompt", b =>
                {
                    b.HasOne("NotesApi.Models.ActionRequest", "ActionRequest")
                        .WithMany()
                        .HasForeignKey("ActionRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotesApi.Models.GameSession", "Session")
                        .WithMany("SessionRollPrompts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesApi.Models.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRequest");

                    b.Navigation("Session");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("NotesApi.Models.ActionRequest", b =>
                {
                    b.Navigation("ChildActions");

                    b.Navigation("Resolution");

                    b.Navigation("RollPrompts");
                });

            modelBuilder.Entity("NotesApi.Models.ApplicationUser", b =>
                {
                    b.Navigation("GamesHosted");
                });

            modelBuilder.Entity("NotesApi.Models.Campaign", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ScheduledSessions");
                });

            modelBuilder.Entity("NotesApi.Models.Character", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("NotesApi.Models.CombatEncounter", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("NotesApi.Models.Game", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("NpcsAndMonsters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("NotesApi.Models.GameSession", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CombatEncounters");

                    b.Navigation("InitiativeEntries");

                    b.Navigation("SessionNotes");

                    b.Navigation("SessionRollPrompts");
                });

            modelBuilder.Entity("NotesApi.Models.Ruleset", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
